"""Global constants"""
VERSION_NUM = '0.2.1'
VIA_INTERFACE_NUM = 1
RAW_HID_BUFFER_SIZE = 32

"""VIA commands"""
GET_PROTOCOL_VERSION = 1
GET_KEYBOARD_VALUES = 2
CUSTOM_SET_VALUE = 7
CUSTOM_GET_VALUE = 8
CUSTOM_SAVE = 9

"""VIA channels"""
CHANNEL_RGB_MATRIX = 3

"""VIA rgb matrix entries"""
RGB_MATRIX_VALUE_BRIGHTNESS = 1
RGB_MATRIX_VALUE_EFFECT = 2
RGB_MATRIX_VALUE_EFFECT_SPEED = 3
RGB_MATRIX_VALUE_COLOR = 4